name: '1 - [feat] Build & Pull Request'

on:
  push:
    branches:
      - 'feature/**'
permissions:
  pull-requests: write

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ github.ref }}
          base: main
          title: "PR AUTOMATICO "
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: |
            This is to show automatic PR creation
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          delete-branch: false

      - name: PR url
        run: |
          echo "Pull Request URL - ${{ steps.create_pr.outputs.pull-request-url }}"
          echo "Deploying to production server on branch $GITHUB_REF"